export default {
    "team": {
        "forwards": [
            {
                "name": "Esteban",
                "first_surname": "Torres",
                "second_surname": "Rivera",
                "birthday": "1999-06-27T00:00:00+00:00",
                "birth_place": "Ciudad Madero, Tamaulipas",
                "weight": 65,
                "height": 1.82,
                "position": "Delantero",
                "number": 15,
                "position_short": "DEL",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/6c0f2264ef654a3ca139c982a842144f.jpg"
            },
            {
                "name": "Abraham Darío",
                "first_surname": "Carreño",
                "second_surname": "Rohan",
                "birthday": "1988-01-13T00:00:00+00:00",
                "birth_place": "Monterrey, Nuevo León",
                "weight": 81,
                "height": 1.83,
                "position": "Delantero",
                "number": 9,
                "position_short": "DEL",
                "last_team": "Puebla F.C.",
                "image": "https://venados.dacodes.mx/img/usr/571cf02d1a194a9e8e190558bbeaa1a0.jpg"
            },
            {
                "name": "Carlos Gael",
                "first_surname": "Acosta",
                "second_surname": "Zavala",
                "birthday": "1992-03-26T00:00:00+00:00",
                "birth_place": "Ahome, Sinaloa,",
                "weight": 64,
                "height": 1.65,
                "position": "Delantero",
                "number": 19,
                "position_short": "DEL",
                "last_team": "Gallos Blancos de Queretaro.",
                "image": "https://venados.dacodes.mx/img/usr/c0274beda3be43a1aed702692cb860e6.jpg"
            },
            {
                "name": "Mathews",
                "first_surname": "Gomes",
                "second_surname": "Da Silva",
                "birthday": "1996-04-09T00:00:00+00:00",
                "birth_place": "Santiago de Querétaro, Querétaro",
                "weight": 72,
                "height": 1.79,
                "position": "Delantero",
                "number": 22,
                "position_short": "DEL",
                "last_team": "Yalmakan FC",
                "image": "https://venados.dacodes.mx/img/usr/5dcad9b75e0740afa869d463dc6011e4.jpg"
            },
            {
                "name": "Freddy",
                "first_surname": "Martín",
                "second_surname": "Mex",
                "birthday": "1987-04-14T00:00:00+00:00",
                "birth_place": "Mérida, Yucatán",
                "weight": 78,
                "height": 1.8,
                "position": "Delantero",
                "number": 14,
                "position_short": "DEL",
                "last_team": "Alebrijes de Oaxaca",
                "image": "https://venados.dacodes.mx/img/usr/9f5a0c40d0134f9e97d4a4a4d2dba900.jpg"
            },
            {
                "name": "Rodrigo",
                "first_surname": "Prieto",
                "second_surname": "Aubert",
                "birthday": "1983-02-08T00:00:00+00:00",
                "birth_place": "Guadalajara, Jalisco",
                "weight": 78,
                "height": 1.8,
                "position": "Delantero",
                "number": 10,
                "position_short": "DEL",
                "last_team": "Zacatepec",
                "image": "https://venados.dacodes.mx/img/usr/550e3ff735c94be481de2b99e3d5ce31.jpg"
            },
            {
                "name": "Saúl",
                "first_surname": "Ramirez",
                "second_surname": "Briceño",
                "birthday": "1998-09-29T00:00:00+00:00",
                "birth_place": "Mérida, Yucatán",
                "weight": 75,
                "height": 1.78,
                "position": "Delantero",
                "number": 26,
                "position_short": "DEL",
                "last_team": "U.N.A.M",
                "image": "https://venados.dacodes.mx/img/usr/b6c60299c3ee4cd0b5495877f93a9226.jpg"
            },
            {
                "name": "Marco",
                "first_surname": "Rossello",
                "second_surname": "Astol",
                "birthday": "1999-10-05T00:00:00+00:00",
                "birth_place": "Canelones, Uruguay",
                "weight": 61,
                "height": 1.69,
                "position": "Delantero",
                "number": 25,
                "position_short": "DEL",
                "last_team": "Venados F.C.",
                "image": "https://venados.dacodes.mx/img/usr/ba2b269a3d33413d877cfa88b2b3a950.jpg"
            }
        ],
        "centers": [
            {
                "name": "Eduardo",
                "first_surname": "Fernández",
                "second_surname": "Aldana",
                "birthday": "1990-04-03T00:00:00+00:00",
                "birth_place": "Mérida, Yucatán",
                "weight": 70,
                "height": 1.74,
                "position": "Mediocampista",
                "number": 7,
                "position_short": "MED",
                "last_team": "Venados F.C.",
                "image": "https://venados.dacodes.mx/img/usr/87dd90bcc04047a785b29ee390999544.jpg"
            },
            {
                "name": "Manuel Alejandro",
                "first_surname": "Vela",
                "second_surname": "Garrido",
                "birthday": "1984-03-28T00:00:00+00:00",
                "birth_place": "Cancún, Quintana Roo",
                "weight": 72,
                "height": 1.72,
                "position": "Mediocampista",
                "number": 11,
                "position_short": "MED",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/8ede6e137f0041d08e91b19ae78b20d9.jpg"
            },
            {
                "name": "Aldo Francisco",
                "first_surname": "Polo",
                "second_surname": "Ramírez",
                "birthday": "1983-10-31T00:00:00+00:00",
                "birth_place": "Ciudad de México",
                "weight": 72,
                "height": 1.75,
                "position": "Mediocampista",
                "number": 8,
                "position_short": "MED",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/0ce11d263ebd40a7b8a17d93c0b134ea.jpg"
            },
            {
                "name": "Francisco Paúl",
                "first_surname": "Uscanga",
                "second_surname": "Gutiérrez",
                "birthday": "1991-03-25T00:00:00+00:00",
                "birth_place": "Coatzacoalcos, Veracruz",
                "weight": 59,
                "height": 1.65,
                "position": "Mediocampista",
                "number": 27,
                "position_short": "MED",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/a4f0e618b8b44de5b11d52eccca7ad03.jpg"
            },
            {
                "name": "Alfonso",
                "first_surname": "Tamay",
                "second_surname": "Sánchez",
                "birthday": "1993-05-13T00:00:00+00:00",
                "birth_place": "Cancún, Quintana Roo",
                "weight": 62,
                "height": 1.65,
                "position": "Mediocampista",
                "number": 13,
                "position_short": "MED",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/3a159406dc224e01bf8db28b59385246.jpg"
            },
            {
                "name": "Jorge José",
                "first_surname": "Ibarra",
                "second_surname": "Sánchez",
                "birthday": "1988-08-29T00:00:00+00:00",
                "birth_place": "Guadalajara, Jalisco",
                "weight": 70,
                "height": 1.7,
                "position": "Mediocampista",
                "number": 29,
                "position_short": "MED",
                "last_team": "Lobos BUAP",
                "image": "https://venados.dacodes.mx/img/usr/475c701a11304f2c84503d6938dbfd67.jpg"
            },
            {
                "name": "Sergio Javier",
                "first_surname": "Nápoles",
                "second_surname": "Saucedo",
                "birthday": "1989-11-23T00:00:00+00:00",
                "birth_place": "Cancún, Quintana Roo",
                "weight": 70,
                "height": 1.68,
                "position": "Mediocampista",
                "number": 18,
                "position_short": "MED",
                "last_team": "Alebrijes de Oaxaca",
                "image": "https://venados.dacodes.mx/img/usr/65c87f504d45440389e4a8dc4a7a6980.jpg"
            },
            {
                "name": "Luis Alberto",
                "first_surname": "Sánchez",
                "second_surname": "Rodríguez",
                "birthday": "1988-02-06T00:00:00+00:00",
                "birth_place": "Tijuana, Baja California",
                "weight": 74,
                "height": 1.75,
                "position": "Mediocampista",
                "number": 21,
                "position_short": "MED",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/2c62e394e817484695cc64fbf24e679f.jpg"
            },
            {
                "name": "Gustavo",
                "first_surname": "Nuñez",
                "second_surname": "Villamil",
                "birthday": "1999-12-03T00:00:00+00:00",
                "birth_place": "Cuernavaca, Morelos",
                "weight": 62,
                "height": 1.76,
                "position": "Mediocampista",
                "number": 30,
                "position_short": "MED",
                "last_team": "Zacatepec",
                "image": "https://venados.dacodes.mx/img/usr/e6621caac54949aca8f19ee2a0cee655.jpg"
            },
            {
                "name": "Damián",
                "first_surname": "Torres",
                "second_surname": "Rodríguez",
                "birthday": "1996-08-26T00:00:00+00:00",
                "birth_place": "Monclova, Coahuila",
                "weight": 59,
                "height": 1.72,
                "position": "Mediocampista",
                "number": 16,
                "position_short": "MED",
                "last_team": "Tigres de la U.A.N.L",
                "image": "https://venados.dacodes.mx/img/usr/003c2db3e2414d05acfbe87147754d27.jpg"
            }
        ],
        "defenses": [
            {
                "name": "Jonathan Alejandro",
                "first_surname": "Sánchez",
                "second_surname": "Hernández",
                "birthday": "1994-03-13T00:00:00+00:00",
                "birth_place": "Ciudad Valles, San Luis Potosí",
                "weight": 70,
                "height": 1.72,
                "position": "Defensa",
                "number": 4,
                "position_short": "DEF",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/9cd3fedb27b24ae79e5b9fe1711b27e9.jpg"
            },
            {
                "name": "Carlos Josafat",
                "first_surname": "Ramos",
                "second_surname": "Ibarra",
                "birthday": "1986-11-12T00:00:00+00:00",
                "birth_place": "Celaya, Guanajuato",
                "weight": 82,
                "height": 1.8,
                "position": "Defensa",
                "number": 6,
                "position_short": "DEF",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/9caeef4f0c0b4c6c9e775b1b5c7e0f1e.jpg"
            },
            {
                "name": "Héctor",
                "first_surname": "Acosta",
                "second_surname": "Quintero",
                "birthday": "1991-11-24T00:00:00+00:00",
                "birth_place": "San Martín Hidalgo, Jalisco",
                "weight": 77,
                "height": 1.78,
                "position": "Defensa",
                "number": 5,
                "position_short": "DEF",
                "last_team": "Toluca",
                "image": "https://venados.dacodes.mx/img/usr/247477a8770644479f87e890a207edfd.jpg"
            },
            {
                "name": "Alberto Carlos",
                "first_surname": "Hernández",
                "second_surname": "Téllez",
                "birthday": "1999-04-27T00:00:00+00:00",
                "birth_place": "Poza Rica de Hidalgo, Veracruz",
                "weight": 74.2,
                "height": 1.75,
                "position": "Defensa",
                "number": 17,
                "position_short": "DEF",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/da93c4623a61448aaf1a63750d9104f4.jpg"
            },
            {
                "name": "Gonzalo",
                "first_surname": "Camargo",
                "second_surname": "Pintos",
                "birthday": "1991-02-16T00:00:00+00:00",
                "birth_place": "Artigas, Uruguay",
                "weight": 70,
                "height": 1.73,
                "position": "Defensa",
                "number": 33,
                "position_short": "DEF",
                "last_team": "Racing Club",
                "image": "https://venados.dacodes.mx/img/usr/99d67413bf85465ba3fa076c8f552a0d.jpg"
            },
            {
                "name": "Adonay",
                "first_surname": "González",
                "second_surname": "Baak",
                "birthday": "1999-07-03T00:00:00+00:00",
                "birth_place": "Motul, Yucatán",
                "weight": 61,
                "height": 1.72,
                "position": "Defensa",
                "number": 32,
                "position_short": "DEF",
                "last_team": "Cantera Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/08ca01c52e5b4af59da9fe273f86e884.jpg"
            },
            {
                "name": "Adrián",
                "first_surname": "Justo",
                "second_surname": "Canto",
                "birthday": "1994-06-06T00:00:00+00:00",
                "birth_place": "Mérida, Yucatán",
                "weight": 75.7,
                "height": 1.78,
                "position": "Defensa",
                "number": 20,
                "position_short": "DEF",
                "last_team": "Potros U.A.E.M",
                "image": "https://venados.dacodes.mx/img/usr/f295f2e9a19b4570baafb3d6a1b38031.jpg"
            },
            {
                "name": "Jair",
                "first_surname": "Díaz",
                "second_surname": "Vázquez",
                "birthday": "1998-08-21T00:00:00+00:00",
                "birth_place": "San Luis Potosí, San Luis Potosí",
                "weight": 81.3,
                "height": 1.81,
                "position": "Defensa",
                "number": 3,
                "position_short": "DEF",
                "last_team": "Tigres de la U.A.N.L",
                "image": "https://venados.dacodes.mx/img/usr/89a7b3221cbf4304b5ba640d9bc10e4e.jpg"
            }
        ],
        "goalkeepers": [
            {
                "name": "Armando",
                "first_surname": "Navarrete",
                "second_surname": "García",
                "birthday": "1980-11-22T00:00:00+00:00",
                "birth_place": "Jacona, Michoacán",
                "weight": 80,
                "height": 1.8,
                "position": "Portero",
                "number": 12,
                "position_short": "POR",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/8729c4bf0cfd491f9e9bc55a08f6d74a.jpg"
            },
            {
                "name": "Rafael",
                "first_surname": "Ramírez",
                "second_surname": "Miranda",
                "birthday": "1992-11-04T00:00:00+00:00",
                "birth_place": "Guadalajara, Jalisco",
                "weight": 75,
                "height": 1.8,
                "position": "Portero",
                "number": 28,
                "position_short": "POR",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/3a83e5fa44114a5d8cf44dcbe6b3b2ee.jpg"
            },
            {
                "name": "Raiko",
                "first_surname": "Arozarena",
                "second_surname": "González",
                "birthday": "1997-03-27T00:00:00+00:00",
                "birth_place": "Pinar del Río, Cuba",
                "weight": 82,
                "height": 1.83,
                "position": "Portero",
                "number": 1,
                "position_short": "POR",
                "last_team": "Venados FC",
                "image": "https://venados.dacodes.mx/img/usr/0c3313a1cbec4112ac376c518a3f9000.jpg"
            }
        ],
        "coaches": [
            {
                "name": "José Carlos",
                "first_surname": "Narvaez",
                "second_surname": "Borges",
                "birthday": "1990-12-05T00:00:00+00:00",
                "birth_place": "Mérida",
                "weight": null,
                "height": null,
                "role": "Fisioterapeuta",
                "role_short": "FIS",
                "image": "https://venados.dacodes.mx/img/usr/6748ec0ba6fc42d1bdce6d54494735e1.jpg"
            },
            {
                "name": "Alberto",
                "first_surname": "Gutiérrez",
                "second_surname": "Castañeda",
                "birthday": "1980-12-13T00:00:00+00:00",
                "birth_place": "León",
                "weight": null,
                "height": null,
                "role": "Utilero",
                "role_short": "UT",
                "image": "https://venados.dacodes.mx/img/usr/563b172180844a57a8194a3c9f86bc69.jpg"
            },
            {
                "name": "Santiago",
                "first_surname": "Dorantes",
                "second_surname": "Solís",
                "birthday": "1982-08-16T00:00:00+00:00",
                "birth_place": "Progreso",
                "weight": null,
                "height": null,
                "role": "Médico",
                "role_short": "MED",
                "image": "https://venados.dacodes.mx/img/usr/0f9e2f7671c24270a4ef2b8777e2485d.jpg"
            },
            {
                "name": "Alejandro",
                "first_surname": "Cabrera",
                "second_surname": "Lara",
                "birthday": "1987-03-01T00:00:00+00:00",
                "birth_place": "Mérida",
                "weight": null,
                "height": null,
                "role": "Utilero",
                "role_short": "UT",
                "image": "https://venados.dacodes.mx/img/usr/f09e63359fab46e6a11afa5bee957f27.jpg"
            },
            {
                "name": "Carlos",
                "first_surname": "Gutiérrez",
                "second_surname": "Barriga",
                "birthday": "1977-11-09T00:00:00+00:00",
                "birth_place": "Distrito Federal, México",
                "weight": null,
                "height": null,
                "role": "Director Técnico",
                "role_short": "DT",
                "image": "https://venados.dacodes.mx/img/usr/d0cedee7c60e4a549c36e7165935f9f7.jpg"
            },
            {
                "name": "Martín",
                "first_surname": "Reyna",
                "second_surname": "Osorio",
                "birthday": "1961-12-08T00:00:00+00:00",
                "birth_place": "Estado de México, México",
                "weight": null,
                "height": null,
                "role": "Auxiliar Técnico",
                "role_short": "AUX",
                "image": "https://venados.dacodes.mx/img/usr/cb4643e4a7d345b5ad99a0e7c961de53.jpg"
            },
            {
                "name": "Gabriel",
                "first_surname": "Souza",
                "second_surname": "Franco",
                "birthday": "1972-11-09T00:00:00+00:00",
                "birth_place": "Montevideo, Uruguay",
                "weight": null,
                "height": null,
                "role": "Preparador Físico",
                "role_short": "PF",
                "image": "https://venados.dacodes.mx/img/usr/119811ad9090415dad2bff3fd7ae363d.jpg"
            },
            {
                "name": "Valtencir",
                "first_surname": "Gomes",
                "second_surname": "Da Silva",
                "birthday": "1969-12-26T00:00:00+00:00",
                "birth_place": "Sao Paulo, Brasil",
                "weight": null,
                "height": null,
                "role": "Auxiliar Técnico",
                "role_short": "AUX",
                "image": "https://venados.dacodes.mx/img/usr/11cf9270068c47119842f812ae933f78.jpg"
            }
        ]
    }
}