export default  [
    {
        "position": 1,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10449/10449.png",
        "team": "Mineros",
        "games": 3,
        "win": 3,
        "loss": 0,
        "tie": 0,
        "f_goals": 9,
        "a_goals": 0,
        "score_diff": 9,
        "points": 10,
        "efec": null
    },
    {
        "position": 2,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/33/33.png",
        "team": "U. de G.",
        "games": 3,
        "win": 2,
        "loss": 0,
        "tie": 1,
        "f_goals": 4,
        "a_goals": 3,
        "score_diff": 1,
        "points": 7,
        "efec": null
    },
    {
        "position": 3,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10962/10962.png",
        "team": "TM Futbol Club",
        "games": 3,
        "win": 2,
        "loss": 0,
        "tie": 1,
        "f_goals": 4,
        "a_goals": 3,
        "score_diff": 1,
        "points": 7,
        "efec": null
    },
    {
        "position": 4,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/21/21.png",
        "team": "Correcaminos",
        "games": 3,
        "win": 2,
        "loss": 0,
        "tie": 1,
        "f_goals": 6,
        "a_goals": 6,
        "score_diff": 0,
        "points": 7,
        "efec": null
    },
    {
        "position": 5,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10721/10721.png",
        "team": "Cimarrones",
        "games": 3,
        "win": 2,
        "loss": 0,
        "tie": 1,
        "f_goals": 4,
        "a_goals": 4,
        "score_diff": 0,
        "points": 7,
        "efec": null
    },
    {
        "position": 6,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/10732/10732.png",
        "team": "Venados",
        "games": 3,
        "win": 2,
        "loss": 0,
        "tie": 1,
        "f_goals": 3,
        "a_goals": 5,
        "score_diff": -2,
        "points": 6,
        "efec": null
    },
    {
        "position": 7,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/11780/11780.png",
        "team": "Alebrijes",
        "games": 3,
        "win": 1,
        "loss": 1,
        "tie": 1,
        "f_goals": 4,
        "a_goals": 2,
        "score_diff": 2,
        "points": 4,
        "efec": null
    },
    {
        "position": 8,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/11221/11221.png",
        "team": "Club Atlético Zacatepec",
        "games": 3,
        "win": 1,
        "loss": 0,
        "tie": 2,
        "f_goals": 5,
        "a_goals": 5,
        "score_diff": 0,
        "points": 3,
        "efec": null
    },
    {
        "position": 9,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/2/2.png",
        "team": "Atlante",
        "games": 3,
        "win": 1,
        "loss": 0,
        "tie": 2,
        "f_goals": 3,
        "a_goals": 4,
        "score_diff": -1,
        "points": 3,
        "efec": null
    },
    {
        "position": 10,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/11578/11578.png",
        "team": "Club Celaya",
        "games": 3,
        "win": 1,
        "loss": 0,
        "tie": 2,
        "f_goals": 2,
        "a_goals": 4,
        "score_diff": -2,
        "points": 3,
        "efec": null
    },
    {
        "position": 11,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/3111/3111.png",
        "team": "Dorados",
        "games": 3,
        "win": 0,
        "loss": 1,
        "tie": 2,
        "f_goals": 2,
        "a_goals": 6,
        "score_diff": -4,
        "points": 1,
        "efec": null
    },
    {
        "position": 12,
        "image": "https://s3.amazonaws.com/lmxwebsite/docs/archdgtl/AfldDrct/logos64x64/11779/11779.png",
        "team": "Cafetaleros de Chiapas FC",
        "games": 3,
        "win": 0,
        "loss": 0,
        "tie": 3,
        "f_goals": 3,
        "a_goals": 7,
        "score_diff": -4,
        "points": 0,
        "efec": null
    }
];